### PR TITLE
v2.0.1

### PR DESCRIPTION
**Pull request by rxm7706**
Pending https://github.com/conda-forge/kfp-server-api-feedstock/pull/26

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
Pending - https://github.com/conda-forge/kfp-server-api-feedstock/pull/26
Would prefer to merge and update all pre-2.0.0 versions of both 
https://github.com/conda-forge/kfp-feedstock/pulls
https://github.com/conda-forge/kfp-server-api-feedstock/pulls

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please restart ci

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @maximerihouey Ready to review - dependency PR for https://github.com/conda-forge/kfp-server-api-feedstock/pull/26 is complete now. Thank you.

**Review by maximerihouey — APPROVED** [review]

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
Hi @maximerihouey ,  This is ready to merge, could you please take a look. Thank you and regards.

**Pull request merged**
