### PR TITLE
Update 1.8.0

### PR DESCRIPTION
**Pull request by maximerihouey**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akchinSTC** [comment]
@maximerihouey - Thank you for getting this done!
Looks like there are some dependency updates still
```
+ pip check
kfp 1.8.0 requires google-api-python-client, which is not installed.
kfp 1.8.0 has requirement click<8,>=7.1.1, but you have click 8.0.4.
kfp 1.8.0 has requirement cloudpickle<2,>=1.3.0, but you have cloudpickle 2.0.0.
kfp 1.8.0 has requirement google-auth<2,>=1.6.1, but you have google-auth 2.6.0.
```

**Comment by manuelwalserqc** [comment]
Hi @maximerihouey and @ckadner, many thanks for the help to create an up-to-date kfp package! Would you agree do act as additional maintainers for the new kfp-pipeline-spec package? If yes I am happy to add you.
https://github.com/conda-forge/kfp-pipeline-spec-feedstock

**Comment by manuelwalserqc** [comment]
@conda-forge-admin, please rerender

**Comment by manuelwalserqc** [comment]
After talking with expert @xhochy I removed dataclass from the dependencies and restricted the package to python>=3.7. py<37 is not build anymore on conda-forge. Including the dependency for all version seems a very bad solution.

**Review by manuelwalserqc — APPROVED** [review]
PR looks good to me now.

**Comment by maximerihouey** [comment]
> @maximerihouey - Thank you for getting this done! Looks like there are some dependency updates still
> 
> ```
> + pip check
> kfp 1.8.0 requires google-api-python-client, which is not installed.
> kfp 1.8.0 has requirement click<8,>=7.1.1, but you have click 8.0.4.
> kfp 1.8.0 has requirement cloudpickle<2,>=1.3.0, but you have cloudpickle 2.0.0.
> kfp 1.8.0 has requirement google-auth<2,>=1.6.1, but you have google-auth 2.6.0.
> ```

I followed the requirements of the upstream package: https://github.com/kubeflow/pipelines/blob/1.8.0/sdk/python/setup.py
But it seems like `pip check` doesn't behave as expected and ask for outdated requirements.

@manuelwalserqc What is the background here to not follow the requirements of the upstream project ? This sounds a bit weird.

Anyway if you feel like the requirements are met don't hesitate to merge the PR.

**Comment by manuelwalserqc** [comment]
Hi @maximerihouey, yes, this inconsistency confused me as well. I do not understand in detail how they build the python packages from the git source. When you download the package from pypi, you can see that the requirements in setup.py are different, and agree with our meta.yaml. I suggest to take the pypi source distributions as reference unless somebody knows better?
https://pypi.org/project/kfp/1.8.0/#files

**Comment by maximerihouey** [comment]
> Hi @maximerihouey, yes, this inconsistency confused me as well. I do not understand in detail how they build the python packages from the git source. When you download the package from pypi, you can see that the requirements in setup.py are different, and agree with our meta.yaml. I suggest to take the pypi source distributions as reference unless somebody knows better? https://pypi.org/project/kfp/1.8.0/#files

@manuelwalserqc In that case let's merge the PR.

**Pull request merged**
