### PR TITLE
Update to 1.7.0

### PR DESCRIPTION
**Pull request by korommatyi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by korommatyi** [comment]
@conda-forge-admin, please rerender

**Comment by korommatyi** [comment]
One error I see is that the package that is called `docstring-parser` on PyPi is called `docstring_parser` on Anaconda. What's the right way to handle this discrepancy? Should I just change the name in the `meta.yaml` or is there a mapping somewhere?

**Comment by maximerihouey** [comment]
> One error I see is that the package that is called `docstring-parser` on PyPi is called `docstring_parser` on Anaconda. What's the right way to handle this discrepancy? Should I just change the name in the `meta.yaml` or is there a mapping somewhere?

Hello, indeed there are some discrepancy between PyPi and Anaconda package namings sometimes, you can see that the original name was correct in the `meta.yaml` file before your changes.

**Comment by korommatyi** [comment]
OK, the other error is similar: the package that is called `kubernetes` on PyPi is called `python-kubernetes` on Anaconda.

**Comment by korommatyi** [comment]
> you can see that the original name was correct in the meta.yaml file before your changes

Oh, sorry, that's indeed true.

**Review by maximerihouey — APPROVED** [review]

**Comment by maximerihouey** [comment]
@korommatyi all the previous versions have now been merge up to this one (https://pypi.org/project/kfp/1.7.0/#history), you just need to rebase this PR so we can merge it.

**Comment by maximerihouey** [comment]
Done by https://github.com/conda-forge/kfp-feedstock/pull/56

**Pull request closed without merging**
